name: Automation of Api using docker

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: ${{ runner.os }}-docker-

    - name: Build Docker image
      run: docker-compose build

    - name: Run tests in Docker container
      run: docker-compose run --rm api-tests
      env:
        API_KEY: ${{ secrets.API_KEY }}

    - name: Get Allure results
      uses: actions/upload-artifact@v4.3.3
      with:
        name: allure-results
        path: allure-results

    - name: Get Allure history
      uses: actions/checkout@v4.1.1
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
